[Refactor] : 챌린지 편집시 필요 정보 API.
KUIT-HealthMate/HealthMate-Backend pull request #64
Opened 2024-08-16 14:30 UTC by park99999

### ✏️ 작업 개요
챌린지 편집시 필요한 정보를 넘겨주는 API를 추가하였습니다.

### ⛳ 작업 분류
- [x] API 생성

### 🔨 작업 상세 내용
1. 태완님 코드 보면서 진행하였습니다.

### 💡 생각해볼 문제
- 냉무

2024-08-16 14:39 UTC, twkwon0417 requested changes
해빗은 id로 넘기는 거만 수정하면 될거 같습니다.

2024-08-16 14:39 UTC, twkwon0417 commented on src/main/java/com/kuit/healthmate/challenge/habit/dto/response/HabitEditResponse.java
> +    private Long habitId;
이거 그냥 habitId가 아니라 id로 넘겨달래

2024-08-17 04:58 UTC, kamothi approved these changes
수고하셨습니다.

2024-08-17 05:11 UTC, twkwon0417 approved these changes

2024-08-17 05:11 UTC, merged